default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: wikibloc_dev

test:
  <<: *default
  database: wikibloc_test

staging:
  <<: *default
  database: wikibloc_staging

production:
  <<: *default
  database: wikibloc_prod
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
